### ISSUE TITLE
Bugs: Flitter effect lost from original

### ISSUE THREAD

**Issue by Aceearly1993** [katriellucas/lecarde-2#17]
There's an effect similar to flitter in the original. But in the reworked versions this effect is lost, thus causing the in game text to look uglier if changed the resolution to something other than default 640x480 resolution, or in the "alt+enter" forced full screen.

![J~{TM9}S1H`}N1OTGB$C@NL](https://user-images.githubusercontent.com/117492706/224273146-725a9759-8b37-4f69-afae-bfe03387f7f4.png)

![image](https://user-images.githubusercontent.com/117492706/224273266-febea6ca-9a44-44c9-b55a-2510a43bc599.png)

**Comment by katriellucas** [comment]
I believe this effect is caused by the game forcing it's 640x480 resolution on the device, so it's actually "no effect", just the normal text rendering. It might be unfixable unless the original font is changed as well.
