### ISSUE TITLE
Localization: add simplified chinese

### ISSUE THREAD

**Issue by katriellucas** [katriellucas/lecarde-2#3]
I've been received quite a lot of requests about this.

Currently all the necessary plain text dialogue and embedded text are already translated, but this project needs pixel artists in order to help matching the general art style of embedded text used by other languages.  Still, I can help the conversion of embedded text if this is deemed necessary, and when some artists found interests to this project. 
If things get worse, there also exists an option to make a separate build and replace all the resources in language slot 5 (which originally serves Japanese language; English language being slot 0) so that it displays simplified Chinese in the alternate build.

**Comment by Aceearly1993** [comment]
Currently all the plain text dialogue strings are already translated, and all necessary embedded text are converted to their original-respective art style and ready for inserting, but it's still in doubt if Simplified Chinese build should be a separated release from original. I fear that it would be too much coding work than creating a separated build.

**Comment by Aceearly1993** [comment]
Inserting done as of 5/14/2023. Maybe also consider doing a separate build as too many plain texts are shared across all languages.
