### ISSUE TITLE
Circlet of Light bug

### ISSUE THREAD

**Issue by pmasterBR** [katriellucas/lecarde-2#58]
In these places it is necessary to use the Circlet of Light, there is a bug that if you access the menu in these dark areas and return to the game, the entire area becomes visible without the need for the Circlet of Light. Thanks for the great project! =,)

**Comment by Aceearly1993** [comment]
Cannot reproduce. A more detailed info containing:
- Which revision of windows OS version did you use
- Which language had you been set to in the game
- A video containing how it is triggered (preferred)
will be good.

Also be warned the game (and the engine the game is built upon) is strongly demanding a completed library of Direct X 9 and Direct X 11 dependencies so check these variables again before you're certainly sure it's a reproduce-able bug.
