### ISSUE TITLE
Keys Not Mapped

### ISSUE THREAD

**Issue by Felipefpl** [katriellucas/lecarde-2#59]
I set the numlock keys below (numlock isnt enabled) to be mapped:

1 - Attack
2 - Jump
3 - Aura
4 - Special
5 - Subscreen
6 - Map

The 5- Subscreen key isnt mapped, the game reports the key as "none" in-game. Tried to use the 7 key to map it and it worked but then the 6 key related to the map in-game changed to "none" just like the 5 key.

Summary - the mapping of keys in the numlock section is bugged.

**Comment by Aceearly1993** [comment]
Hmmm, this is a very rare key position for a reason that we rework team all missed the check...  Not a very easy target to ease unless to ruin the keyboard structure again from zero just for a different keyboard plugin, which I myself consider not very worth the labor. Also the "none" return value is more of a universal hardware thing that can also happen in game engines other than fusion, and not really an issue exclusive in this game.
