### ISSUE TITLE
No Scenery Block? - Bulld 1.5.4

### ISSUE THREAD

**Issue by Felipefpl** [katriellucas/lecarde-2#63]
This one is hard to reproduce but perhaps it can be done:

Sometimes the character gets stuck in a certain place and then it starts moving through the scenery, Apparently this can happen anywhere but i had this problem the most on Horror Gallery.

You can move the character till he gets for example in the floor above where you were or even going to the left side of the scenery.

**Comment by Aceearly1993** [comment]
Never encountered anything similar to this for all these years. Given nobody ever mentioned similar issue it's better left the structure the shape what it was.
